# Generated by Django 3.0.7 on 2022-04-09 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('employee_number', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(default='', max_length=50)),
                ('mang_name', models.CharField(default='', max_length=50)),
                ('message', models.CharField(default='', max_length=500)),
                ('requested_date', models.DateField(default=django.utils.timezone.now)),
                ('created_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(default='', max_length=50)),
                ('mang_name', models.CharField(default='', max_length=50)),
                ('message', models.CharField(default='', max_length=500)),
                ('requested_date', models.DateField(default=django.utils.timezone.now)),
                ('created_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=400)),
                ('priority', models.CharField(default='', max_length=10)),
                ('deadline', models.DateField(default=django.utils.timezone.now)),
                ('created_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
